### ISSUE TITLE
GMK Lux Color Codes

### ISSUE THREAD

**Issue by andytham** [matrixzj/matrixzj.github.io#3]
According to [this](https://geekhack.org/index.php?topic=103859.msg2901004#msg2901004) post on geekhack.

RAL 000 15 00 (black)
RAL 080 70 60 (yellow)

**Comment by matrixzj** [comment]
Thanks for sharing this info. Color has been added to [GMK Lux Page](https://matrixzj.github.io/docs/gmk-keycaps/Lux/)
