### ISSUE TITLE
SA Dream Eater color codes

### ISSUE THREAD

**Issue by mihihodie** [matrixzj/matrixzj.github.io#4]
https://matrixzj.github.io/docs/sa-keycaps/DreamEater/

For the SA Dream Eater set,  it was released on the GB runners Discord what the color codes are. 
(Using the Main kit as reference)

Keys left to right: VBV / BFL / #3b6f75 / BED / BBI
Legends left to right: BBI / RCJ

as said here:

https://discordapp.com/channels/409423094868869121/713410288120102966/714852614277300345

**Comment by matrixzj** [comment]
Thanks for info sharing.

It has been updated in [SA Dream Eater page](https://matrixzj.github.io/docs/sa-keycaps/DreamEater/#info)
